### ISSUE TITLE
UE4 Plugin Cannot Be Packaged For Shipping/Distributing

### ISSUE THREAD

**Issue by CJRobertson** [ManusVR/Manus-Unreal#1]
When attempting to package a game for public or development distributing, the IDE (for me Visual Studio 2015)/Unreal Engine 4 packaging tool will not include the Manus UE4 plugin during the packaging process because the Manus code is initiated and that causes a fatal error in the process for whatever reason which stops the whole packaging process.

Due to this issue any UE4 games using Manus-VR cannot be packaged which means there is no way to distribute the final product or even test builds.

I'll attach screenshots of my findings asap.

**Comment by Armada651** [comment]
This should be fixed in the new release, please try it out: https://github.com/ManusVR/Manus-Unreal/releases/tag/0.1.1

**Comment by CJRobertson** [comment]
Sorry it took so long to reply back. I attempted to package the plugin again using the example project that is included and other personal projects and I unfortunately still have issues that prevents the game from being packaged. There is only one error this time and its due to something with the the Manus Library not being initialized. 


Attached is a copy of the UE4 Packaging log.


[ManusUnrealPlugin_packaging_log.txt](https://github.com/ManusVR/Manus-Unreal/files/139490/ManusUnrealPlugin_packaging_log.txt)

What I do is go to the 'File' menu-->Package Project-->Windows-->Windows (64-bit). From there it will go through the building, cooking and packaging process and you'll see some errors which is normal to see but then for me there will be that one single error of the Manus Library not being able to be initialized.

**Comment by Armada651** [comment]
@CJRobertson This issue should be solved in the latest git commit, could you try it out?

**Comment by CJRobertson** [comment]
@Armada651 I attempted to package a project (both a personal and the included with the plugin) and both packaged without zero errors which is awesome! But new problem which I'm not sure if its on my end since I haven't had time to play with everything after the packaging test. 

New Issue:

If you start the packaged game (which will be in a folder called WindowsNoEditor by default) the map, Manus hand meshes and so on will load fine BUT the gloves will not initialize which results in no movements from the gloves/hands. I know they don't initialized because the LED on the gloves do not stay lit but instead continuously blink.

**Comment by Armada651** [comment]
@CJRobertson If it works fine in the editor, that indicates the plugin doesn't initialize properly. Probably another packaging issue. We'll look into it.

**Comment by CJRobertson** [comment]
This is the newest log when I attempt to package just for reference.

[ManusPackagingLog.txt](https://github.com/ManusVR/Manus-Unreal/files/142276/ManusPackagingLog.txt)

**Comment by CJRobertson** [comment]
I know GDC is getting close so I'm not expecting anything but any chance on a fix or ETA on fix?

**Comment by ManusMachina** [comment]
We reached out to an Unreal specialist who will be optimizing and streamlining the SDK. 
He plans to have it finalized tomorrow end of day, I will let you know when the new version becomes available. So sit back, we've got our top man on this ;)

**Comment by Armada651** [comment]
@CJRobertson Please try the latest build, should be fixed now.

**Comment by CJRobertson** [comment]
Good news and news about something that I'm helping address myself in a Pull Request.

The plugin compiles and packages no problem and the packaged game initializes both gloves. Thank you for the hard work! The "new issue" that I found though is that the UE4 specialist you guys had streamline and optimize your SDK used Unreal Engine 4.10.X but the included demo project is based on 4.9.X. If you compile the plugin with a project based on 4.9 then the plugin will not work so if new users wanted to try out the gloves first using the demo project then the plugin compile but not allow the gloves to work.

The suggestion here is to have separate repos dedicated to each engine version to avoid this kind of confusion.

**Comment by Cyx69** [comment]
@CJRobertson: Sorry, for breaking the UE 4.9 version of the left hand BP and causing any troubles! 
Totally forgot that I worked already on 4.10. Please use this fixed version:
https://github.com/Cyx69/Manus-Unreal/blob/master/Content/LeftHand.uasset

**Comment by CJRobertson** [comment]
No worries, haha. I would have fixed just the left hand but I wasn't sure if you guys were trying to migrate everything to 4.10 or no so I just assumed that was the case. 

I did test it again though using the Left Hand Animation Blueprint you linked me to along with all the other commits. Everything works perfectly during compiling, packaging and while developing in the editor so we are good to go now! Thank you guys for the help.

(closing issue)
